<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Welcome' => 'Bienvenido',
    'Action' => '',
    'App ID' => '',
    'Are you sure you want to delete this item?' => '',
    'City ID' => '',
    'City Name' => '',
    'Code' => '',
    'Content' => '',
    'Controller' => '',
    'Country Code' => '',
    'Country ID' => '',
    'Country Name' => '',
    'Create' => '',
    'Create By' => '',
    'Create Email Template' => '',
    'Create On' => '',
    'Create User' => '',
    'Created By' => '',
    'Created On' => '',
    'Delete' => '',
    'Description' => '',
    'Edit' => '',
    'Email' => '',
    'Email Templates' => '',
    'First Name' => '',
    'History' => '',
    'ID' => '',
    'Icon Class' => '',
    'Is Active' => '',
    'Is Delete' => '',
    'Is Visible' => '',
    'Label' => '',
    'Last Name' => '',
    'Level' => '',
    'Login Time' => '',
    'Logout Time' => '',
    'M ID' => '',
    'Modified By' => '',
    'Modified On' => '',
    'Modify By' => '',
    'Modify On' => '',
    'Name' => '',
    'Parent ID' => '',
    'Password' => '',
    'Pincode' => '',
    'Profile Image' => '',
    'Projects' => '',
    'Reset' => '',
    'Role Name' => '',
    'Search' => '',
    'Sort On' => '',
    'State ID' => '',
    'State Name' => '',
    'Status' => '',
    'Type Name' => '',
    'Ul ID' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Ur ID' => '',
    'Url' => '',
    'User ID' => '',
    'User Image' => '',
    'Username' => '',
    'Users' => '',
    'Ut ID' => '',
    'View' => '',
   // 'Welcome' => '',
];
